-- MySQL Script generated by MySQL Workbench
-- Wed Feb 20 17:32:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bicycle_hire
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bicycle_hire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bicycle_hire` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bicycle_hire` ;

-- -----------------------------------------------------
-- Table `bicycle_hire`.`bicycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle_hire`.`bicycle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `daily_rental_price` DECIMAL(10,0) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idbicycle_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 105
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicycle_hire`.`point_hire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle_hire`.`point_hire` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idpoint_hire_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicycle_hire`.`point_hire_bicycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle_hire`.`point_hire_bicycle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_point_hire` INT(11) NOT NULL,
  `id_bicycle` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `id_point_hire`, `id_bicycle`),
  UNIQUE INDEX `idpoint_hire_bicycle_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `id_bicycle_UNIQUE` (`id_bicycle` ASC) VISIBLE,
  INDEX `id_point_hire_idx` (`id_point_hire` ASC) VISIBLE,
  INDEX `id_bicycle_idx` (`id_bicycle` ASC) VISIBLE,
  CONSTRAINT `id_bicycle`
    FOREIGN KEY (`id_bicycle`)
    REFERENCES `bicycle_hire`.`bicycle` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `id_point_hire`
    FOREIGN KEY (`id_point_hire`)
    REFERENCES `bicycle_hire`.`point_hire` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicycle_hire`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle_hire`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `idRole_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicycle_hire`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle_hire`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(120) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  `first_Name` VARCHAR(120) NOT NULL,
  `last_Name` VARCHAR(120) NOT NULL,
  `status` VARCHAR(120) NOT NULL,
  `registration_Date` DATETIME NOT NULL,
  `balance` DECIMAL(10,0) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `id_Role` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `id_role_idx` (`id_Role` ASC) VISIBLE,
  CONSTRAINT `id_role`
    FOREIGN KEY (`id_Role`)
    REFERENCES `bicycle_hire`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 106
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicycle_hire`.`bicycle_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicycle_hire`.`bicycle_order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_point_hire_bicycle` INT(11) NOT NULL,
  `time_order` DATETIME NOT NULL,
  `time_rental` INT(11) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idbicycle_order_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_point_hire_bicycle_idx` (`id_point_hire_bicycle` ASC) VISIBLE,
  CONSTRAINT `id_point_hire_bicycle`
    FOREIGN KEY (`id_point_hire_bicycle`)
    REFERENCES `bicycle_hire`.`point_hire_bicycle` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `bicycle_hire`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



